version: "3.8"

services:
    umbraco-db:
      image: mcr.microsoft.com/mssql/server:latest
      container_name: umbraco-db
      user: root
      env_file: ./env/mssql.env
      volumes:
        - umbraco.db:/var/opt/mssql/data
      restart: unless-stopped
      ports:
        - '7000:1433'

    cache:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '7001:6379'
      volumes: 
        - cache:/data
volumes:
  umbraco.db:
  cache:
    driver: local